### create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "tes1tq2@q.com",
  "password": "test"
}

### sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "testq2@q.com",
  "password": "test"
}

### find a user by id
GET http://localhost:3000/auth/2

### find all users
GET http://localhost:3000/auth?email=11@qq.com

### delete a user by id
DELETE http://localhost:3000/auth/2

### update a user by id
PATCH http://localhost:3000/auth/32
Content-Type: application/json


{
  "email": "11@qq.com",
  "password": "11"
}


### set color
GET http://localhost:3000/auth/colors/blue

### get color
GET http://localhost:3000/auth/colors

### who am i
GET http://localhost:3000/auth/whoami

### who am i
GET http://localhost:3000/auth/whoami2

### sign signout
POST http://localhost:3000/auth/signout
